version: "3.9"

services:
  db:
    image: postgres:13-alpine
    container_name: postgres_ecom
    networks:
      - ecom_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  ecommerce:
    build: .
    container_name: django_ecom
    ports:
      - 8000:8000
    networks:
      - ecom_network
    volumes:
      - data:/ecommerce/volume/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_HOST=db
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

networks:
  ecom_network:
    driver: bridge

volumes:
  data: {}
  postgres_data: {}