version: "3"

services:
  db:
    image: postgres:13-alpine
    container_name: postgres_ecom
    restart: always
    networks:
      - ecom_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  ecommerce:
    build: .
    container_name: django_ecom
    restart: always
    ports:
      - 7000:7000
    networks:
      - ecom_network
    volumes:
      - data:/ecommerce/volume/data
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --noinput &&
             python manage.py runserver 0.0.0.0:7000"
    depends_on:
      - db

networks:
  ecom_network:
    driver: bridge

volumes:
  data: {}
  postgres_data: {}